### ISSUE TITLE
Feature that cut silent parts

### ISSUE THREAD

**Issue by theRAGEhero** [antiboredom/videogrep#107]
Hello and thank you for your awesome job,

would it be possible to add a feature to remove the silent parts and edit them in one file? 

I mean that at the end you have a file with always someone that is talking. This would be awesome for vlogs!

Thank you,
Alessandro

----

edit. Is this script making that? https://github.com/antiboredom/videogrep/blob/master/examples/parts_of_speech.py

**Comment by antiboredom** [comment]
hi @theRAGEhero - I'm not sure about adding it as a feature, but I have just made an example script that you can run to remove silences. You can find it here: https://github.com/antiboredom/videogrep/blob/master/examples/remove_silence.py

**Comment by antiboredom** [comment]
hi! Sorry, I should have mentioned that will only work with videos that you transcribe with videogrep (so no .vtt files from youtube). It also might mean that it can't find silences for other reasons, although I'm not sure why that would be... What transcription are you using?

**Comment by theRAGEhero** [comment]
I'm using an .srt file generated by kdenlive (Volk). 

The format is:

```
1
00:00:00,840 --> 00:00:03,030
hello hello hello

2
00:00:03,150 --> 00:00:05,606
hello hello hello
```

**Comment by antiboredom** [comment]
gotcha - give me a moment and I'll see if I can get it working with that...

**Comment by antiboredom** [comment]
@theRAGEhero can you re-download and try the script again?

**Comment by theRAGEhero** [comment]
It works very well! The only thing I need to fix is the output quality that right now is lower than the original video.
