### ISSUE TITLE
Audio-only mode?

### ISSUE THREAD

**Issue by wiseman** [antiboredom/videogrep#114]
Just checking if anyone knows of a fork or similar tool that can be used on pure audio, without video.  That is, I have thousands of mp3s with transcription info (as .srt or .vtt format), and I want to generate a supercut mp3.

**Comment by antiboredom** [comment]
I'd like to add this in officially. For the moment you can use the sister project [audiogrep](https://github.com/antiboredom/audiogrep) although it's currently unmaintained...

**Comment by antiboredom** [comment]
This is working now, thanks to @charliemacquarie
