### ISSUE TITLE
Subtitles from freeview transport streams

### ISSUE THREAD

**Issue by stuaxo** [antiboredom/videogrep#12]
It would be good if it could extract these somehow, as it would make it super easy to capture stuff off the TV.

[Freeview is the UK digital tv standard (DVB-T), I think it's similar in other places tooo]

Some  quick googling + I found this

http://ccextractor.sourceforge.net/

Which seems like it might be able to extract subs from pretty much anything and convert to srt

**Comment by stuaxo** [comment]
I guess the correct phrasing was subtitles from DVB transport streams

https://forum.videohelp.com/threads/382820-Extract-subtitles-from-MPEG-TS-file-%28DVB-Subtitle%29-using-ffmpeg

At some point I mean to connect my collection of raspberry pis and TV tuners and dump out all channels, not quite sure on the supercut possibilities !

**Comment by antiboredom** [comment]
I'm still interested in this but don't have time to take a look right now, or the ability to test - but if you figure something out please reopen the issue!
