### ISSUE TITLE
from . import vtt, srt, sphinx, fcpxml

### ISSUE THREAD

**Issue by dav3shanahan** [antiboredom/videogrep#124]
How do I resolve this issue that prevents the program from running? 
"Traceback (most recent call last):
  File "C:\videogrep-master\videogrep\videogrep.py", line 7, in <module>
    from . import vtt, srt, sphinx, fcpxml
ImportError: attempted relative import with no known parent package"

**Comment by tagraf** [comment]
(Not a programmer but a guess)
I think you may need to do:
pip install vtt srt sphinx fcpxml

But yeah, those modules should be included within the package -- or during the installation process.
