### ISSUE TITLE
 Issue with Searching Single-Letter Words

### ISSUE THREAD

**Issue by delmenhorst** [antiboredom/videogrep#135]
When attempting to search for single-letter words, such as "i", using the fragments function, the expected behavior does not occur. Instead, it just slices the entire video.

**Comment by antiboredom** [comment]
Hi there — videogrep uses regular expression syntax for search. This means that searching for “i” will grab all words that contain an “i” in them. To ensure that you’re getting an exact match, put a caret symbol before the search term and a dollar sign after it. So for “i” you would do: “^i$”.
