### ISSUE TITLE
Possible to specify amount of words on each side ?

### ISSUE THREAD

**Issue by stuaxo** [antiboredom/videogrep#22]
I was doing some searches on "I" and get a lot on either side, for instance:

```
94.299 to 96.85:    our long-term economic plan and I see that as a demand for us to deliver
```

Is it possible to control the max number of words on each side ?

**Comment by stuaxo** [comment]
Fair enough, I think I worded this weirdly, 8 years later and I don't know what I meant.

**Comment by antiboredom** [comment]
hi - I'm finally doing some work to clean up the project and this is now integrated in the new beta: https://github.com/antiboredom/videogrep/tree/v2beta

**Comment by stuaxo** [comment]
Fantastic, thanks :)
