### ISSUE TITLE
Create .srt file for created supercut movie

### ISSUE THREAD

**Issue by moonhouse** [antiboredom/videogrep#23]
Since the captions are already available in the source files videogrep could produce a new  .srt file for the created supercut file with correct timings.

**Comment by timelf123** [comment]
Any chance of reviving this feature? I want to do some automation in AE with the VTT but transcribing the output file has mixed results

**Comment by antiboredom** [comment]
Sure! This does seem like a good feature and wouldn’t be that tricky to add (and feel free to take a crack at it if you are so inclined).

**Comment by bencomp** [comment]
I took a crack and added a flag that outputs WebVTT next to the supercut file in #121 :)
