### ISSUE TITLE
Replace subtitle tracks by voice recognition

### ISSUE THREAD

**Issue by louismullie** [antiboredom/videogrep#26]
Would you be interested in an experimental branch using actual voice recognition instead of subtitle tracks to make the video cuts?

**Comment by mxisaac** [comment]
Has anyone explored this further?  I'm a video editor and something similar to this exists in Avid Media Composer, where you feed it a transcription, and then using that data it can narrow down much more precisely what people are saying.  If you had subtitles/timecode AND voice recognition, I'd imagine you could pull the exact words you want every time.  And if it falls under a certain threshold, just output the same way it outputs now, pull the whole section.

**Comment by antiboredom** [comment]
Hey - this is actually now integrated (sort of). You have to install pocketsphinx to make it work. Check out the readme for instructions.
