### ISSUE TITLE
ImportError: No module named pattern.search

### ISSUE THREAD

**Issue by adekbadek** [antiboredom/videogrep#31]
Hi, I'm new to Python, so maybe I've made some stupid mistake. But I followed the instructions, double-checked if the requirements have installed, but still I get this output:

Traceback (most recent call last):
  File "videogrep.py", line 7, in <module>
    import search as Search
  File "/Users/adam/Desktop/videogrep/search.py", line 2, in <module>
    from pattern.search import Pattern, STRICT, search
ImportError: No module named pattern.search

I'm on a mac and pattern is in /usr/local/lib/python2.7/site-packages, so there should be no problem.

**Comment by nealewillis** [comment]
and here...

**Comment by marclundgren** [comment]
can confirm this is still happening today (on yosemite)

**Comment by marclundgren** [comment]
`pip install -r requirements.txt`

...
`error: could not create '/Library/Python/2.7/site-packages/pattern': Permission denied`

try `sudo pip install -r requirements.txt`
