### ISSUE TITLE
search-type franken not working

### ISSUE THREAD

**Issue by opensourcegrappler** [antiboredom/videogrep#36]
Hi,

When using "-st franken" the search term is not found, if I use "-st pos" then the search term is found. Obviously I'm doing this on the same file.

The documentation (README) is not very clear on how to use the franken option. An example would help a lot. 

Great project otherwise, my new favourite tool.

**Comment by billyfung** [comment]
I'm not sure franken is supported yet

**Comment by lowtronik** [comment]
i have the same issue

**Comment by billyjacobson** [comment]
Is franken still unsupported?
