### ISSUE TITLE
Is there any plan for python3 

### ISSUE THREAD

**Issue by ZedYeung** [antiboredom/videogrep#42]

**Comment by antiboredom** [comment]
Absolutely - there are a few dependencies that add extra functionality which require python2 but they aren't really essential...

**Comment by xenu256** [comment]
I've just found this package when working on one project and as work only with Python 3, I probably can do it, will see tomorrow.

**Comment by Albertkaruna** [comment]
My system as Python 3, So I can't install it, please anyone tell me how to install it.

**Comment by xenu256** [comment]
@Albertkaruna , my fork currently runs on Python 3.6, but it's not yet tested and also requires audiogrep and modified pattern (which most probably wouldn't work):

```text
https://github.com/xenu256/videogrep
https://github.com/xenu256/audiogrep
https://github.com/xenu256/pattern
```

**Comment by antiboredom** [comment]
@xenu256 does pattern officially support python3 at this point?

Also videogrep uses pattern for two search options: the hypernym and parts-of-speech search. I'm wondering how essential those are. Maybe the library shouldn't include pattern by default, and those search options become available only if you have pattern installed. Thoughts?

**Comment by xenu256** [comment]
Doesn't work, it has 1M lines of code and uses sgmllib, which is removed from Python base, everything should be rewritten in lxml I suppose. Probably that just one of problems. I only managed to install it, but, of course, when calling respective functions pattern would fail. Their issue page talks about Beautiful Soup, which also can be used to solve the problem. Probably even easier can be just use NLTK (or just wait for pattern3), but I didn't dig into it much.

**Comment by xenu256** [comment]
I have decided to port it to nltk, dropping pattern altogether.

what is re_search here? should be re.search?

```text
possible_words = re_search(text, pos)
```

**Comment by xenu256** [comment]
Never mind, found it, it is just not imported.

**Comment by kerstin** [comment]
Hi there, I've read through all comments in here but... still am not any wiser wrt the status of this/the original question.

**Comment by antiboredom** [comment]
should work with python3 now - I've moved pattern.en to an optional requirement.
