### ISSUE TITLE
videogrep ffmpeg mosaic

### ISSUE THREAD

**Issue by kadallah** [antiboredom/videogrep#43]
Seeing as videogrep uses ffmpeg to concat the videos together, is it possible to create a [mosaic](https://trac.ffmpeg.org/wiki/Create%20a%20mosaic%20out%20of%20several%20input%20videos) rather than a single long video? The ultimate goal would be to have the videos aligned so that the search text is all being said at the same time in the mosaic, but just outputting it as a mosaic first seems like a good enough entry point to me. 

Thanks!

**Comment by BaddMann** [comment]
If you export all the clips as separate clips, you could then use moviepy to mosaic the clips and time them, yes it's not one single command, but should be relatively easy from there.

Just a thought.
