### ISSUE TITLE
The Mac App! Wow

### ISSUE THREAD

**Issue by BaddMann** [antiboredom/videogrep#44]
I've been trying to look into GUI interfaces and your videogrep beta app is fantastic! 
Are you planning on releasing the source?
If not, can you please tell me what frameworks you're using?
Thank you, 
Great Job

**Comment by BaddMann** [comment]
What I've found so Far: 
https://www.fyears.org/2017/02/electron-as-gui-of-python-apps-updated.html
Not sure it's exactly what you've done but appears to be a good start to reproduce Videogrep app like capabilities

**Comment by pietrop** [comment]
@BaddMann this was a while back, but it's related to this issue https://github.com/antiboredom/videogrep/issues/38

The code is done using [electron](https://electronjs.org/). As a workaround for now, if you download the desktop app and righ click onto `Show Package Content` you'd be able to see most of the electron codebase
