### ISSUE TITLE
Not able to install videogrep in Arch Linux

### ISSUE THREAD

**Issue by eerie** [antiboredom/videogrep#45]
$ sudo pip install videogrep
Collecting videogrep
  Downloading videogrep-0.5.0.tar.gz
Requirement already satisfied: audiogrep in /usr/lib/python3.6/site-packages (from videogrep)
Collecting Pattern (from videogrep)
  Downloading pattern-2.6.zip (24.6MB)
    100% |████████████████████████████████| 24.6MB 19kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-u2qtl19h/Pattern/setup.py", line 40
        print n
              ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-u2qtl19h/Pattern/

**Comment by billyfung** [comment]
videogrep is not python3 compatible at the moment
