### ISSUE TITLE
 No subtitle files were found

### ISSUE THREAD

**Issue by Albertkaruna** [antiboredom/videogrep#48]
when I run a command :
`python videogrep.py --input C:\Users\Guestuser\Desktop\Newfolder --search 'big'`

it shows the following error

[!] No subtitle files were found.
Traceback (most recent call last):
  File "videogrep.py", line 422, in <module>
    main()
  File "videogrep.py", line 418, in main
    videogrep(args.inputfile, args.outputfile, args.search, args.searchtype, args.maxclips, args.padding, args.demo, args.randomize, args.sync, args.use_transcript)
  File "videogrep.py", line 357, in videogrep
    composition = compose_from_srts(srts, search, searchtype, padding=padding, sync=sync)
  File "videogrep.py", line 254, in compose_from_srts
    for srt in srts:
TypeError: 'bool' object is not iterable

This is my folder structure.
![image](https://user-images.githubusercontent.com/12850583/27761418-23833248-5e79-11e7-91d9-637e4b4d06ea.png)

Please, anyone, tell me the solution.

**Comment by raj6996** [comment]
Albertkaruna, how did you solve this?
