### ISSUE TITLE
"pip install pattern" error

### ISSUE THREAD

**Issue by raj6996** [antiboredom/videogrep#58]
G:\Python3.7>pip install --upgrade setuptools
Successfully installed setuptools-40.0.0

G:\Python3.7>pip install pattern
Collecting pattern
  Using cached https://files.pythonhosted.org/packages/bf/50/d09941d53416f2a86676bd0dc341d5968b599a763b73f5d13f51c57b5641/pattern-2.6.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Yell\AppData\Local\Temp\pip-install-xbhhy0js\pattern\setup.py", line 40
        print n
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(n)?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Yell\AppData\Local\Temp\pip-install-xbhhy0js\pattern\

Will you take a look into this? thanks.

**Comment by billyfung** [comment]
Pattern is python 2 only afaik 
https://github.com/clips/pattern/issues/62
