### ISSUE TITLE
No subtitle files were found!

### ISSUE THREAD

**Issue by raj6996** [antiboredom/videogrep#60]
> C:\Python37>python C:\Python37\myvideogrep.py -i "C:\A" --search "Not you" -o "C:\test.mp4"python C:\Python37\myvideogrep.py -i "C:\A" --search "Not you" -o "C:\test.mp4"
> usage: myvideogrep.py [-h] --input [INPUTFILE [INPUTFILE ...]]
>                       [--search SEARCH]
>                       [--search-type {re,pos,hyper,fragment,franken,word}]
>                       [--use-transcript] [--use-vtt] [--max-clips MAXCLIPS]
>                       [--output OUTPUTFILE] [--export-clips] [--demo]
>                       [--randomize] [--youtube YOUTUBE] [--padding PADDING]
>                       [--resyncsubs SYNC] [--transcribe] [--ngrams NGRAMS]
> myvideogrep.py: error: unrecognized arguments: C:\Python37\myvideogrep.py
>  
> C:\Python37>python C:\Python37\myvideogrep.py -i "G:\I" -s "All" -st word -o test.mp4
> [!] No subtitle files were found.
> Traceback (most recent call last):
>   File "C:\Python37\myvideogrep.py", line 3, in <module>
>     videogrep.main()
>   File "C:\Python37\lib\site-packages\videogrep\videogrep.py", line 528, in main
>     videogrep(args.inputfile, args.outputfile, args.search, args.searchtype, args.maxclips, args.padding, args.demo, args.randomize, args.sync, args.use_transcript, args.use_vtt, args.export_clips)
>   File "C:\Python37\lib\site-packages\videogrep\videogrep.py", line 456, in videogrep
>     composition = compose_from_srts(srts, search, searchtype)
>   File "C:\Python37\lib\site-packages\videogrep\videogrep.py", line 317, in compose_from_srts
>     for srt in srts:
> TypeError: 'bool' object is not iterable

After long time fixing #57, I got this new error like  this>
#48 
will any Windows Users fix this issue, it will be helpful for me. thanks.

**Comment by denny64** [comment]
@raj6996 any luck on this?

**Comment by raj6996** [comment]
No man...

**Comment by sonukick** [comment]
```
`for f in inputfile:
        filename = f.split('.')
        filename[-1] = 'srt'
        srt = '.'.join(filename)
        if os.path.isfile(srt):
            srts.append(srt)

    if len(srts) == 0:
        print("[!] No subtitle files were found.")
        return False

```
splitting by '.' change it to '/' or modify the above function to fetch sub titles autmoatically from the folder.

**Comment by inimaz** [comment]
I had the same issue. This mostly comes when there are "." in the name of the file. An **ugly** workaround might be to always have the video and subtitle files at the source directory.

What I do is to copy them to source repository and then delete them

```
RESOURCES_DIRECTORY = './resources/'
originalfile_name = RESOURCES_DIRECTORY + video_file_name
original_sbtfile_name = RESOURCES_DIRECTORY + subt_name

shutil.copyfile(originalfile_name, video_file_name)
shutil.copyfile(original_sbtfile_name, subt_name)

# YOUR CODE

os.remove(video_file_name)
os.remove(subt_name)
```

Once the PR above is merged, you will not need this and you can use right away filenames like
"./resources/my_filename.mp4"

**Comment by DyeffersonAz** [comment]
This project seems abandoned. Is there any fork of it? This issue is from 2018 and was not yet resolved. Is there a conclusion of all that? I can't make this work, the software doesn't recognize any of my files yet in 2020/2021. This is the second time I'm trying this program this year.

**Comment by antiboredom** [comment]
this should now be fixed in the new beta
