### ISSUE TITLE
Trouble running videogrep

### ISSUE THREAD

**Issue by Kaelinator** [antiboredom/videogrep#63]
When I try to run videogrep through cli, I get 
```
'videogrep' is not recognized as an internal or external command,
operable program or batch file.
```
Running Windows 10, it seems that in `Python36-32\Scripts`, it seems that the `videogrep` file is not a `.exe` like the others. I believe this is the culprit, but I'm not sure how to make it a `.exe`.

**Comment by DarkCeptor44** [comment]
> When I try to run videogrep through cli, I get
> 
> ```
> 'videogrep' is not recognized as an internal or external command,
> operable program or batch file.
> ```
> 
> Running Windows 10, it seems that in `Python36-32\Scripts`, it seems that the `videogrep` file is not a `.exe` like the others. I believe this is the culprit, but I'm not sure how to make it a `.exe`.

I'm having the same problem, to help everyone I have more information, the file `videogrep` is actually a small python script with the content:
```
#!c:\users\msi gx63vr\appdata\local\programs\python\python36\python.exe

from videogrep import videogrep
if __name__ == '__main__':
    videogrep.main()
```

When I changed that file to `.py` it ran but it says `ImportError: cannot import name 'videogrep'`, so I tried inputting each line in a python cmd in another directory and it does import, but when I input the `videogrep.main()` it says `AttributeError: 'function' object has no attribute 'main'`, then I realized it's a function so I ran `videogrep()` and it gave me a somewhat "successful" error: `TypeError: videogrep() missing 4 required positional arguments: 'inputfile', 'outputfile', 'search', and 'searchtype'`.

But it's still impossible to run it from CLI, there's the same `ImportError: cannot import name 'videogrep'` error.

**Comment by garstka** [comment]
Workaround on Windows 10:
```
python -mvideogrep.videogrep --input input.mp4 --search searchterm --use-vtt
```

**Comment by DarkCeptor44** [comment]
> Workaround on Windows 10:
> 
> ```
> python -mvideogrep.videogrep --input input.mp4 --search searchterm --use-vtt
> ```

It works perfectly, unfortunately I cannot close this issue.
