### ISSUE TITLE
Match Silence as in the (Total Recall) example

### ISSUE THREAD

**Issue by H8to** [antiboredom/videogrep#69]
Hey!

This is a great project :+1: 
How may I match on silence?

You added one example with the output, which sadly has been removed on Youtube:
`All the one to two second silences in "Total Recall"`

Would be a great help for my current project to be able to do this :)

**Comment by H8to** [comment]
Must have overlooked silence.py :)

**Comment by olliepalmer** [comment]
Am I correct in thinking that in order to use `silence.py` you need a .srt file, rather than a pocketsphinx transcript? And if so, is there a way to convert a pocketsphinx transcript into a .srt? 

Apologies if I’m being a doofus and missing something obvious.
