### ISSUE TITLE
Please install pattern: pip install https://github.com/clips/pattern/archive/development.zip (but its installed)

### ISSUE THREAD

**Issue by moeC137** [antiboredom/videogrep#80]
if i try:

videogrep --input xy.mkv --search xyz --search-type hyper

i get:
Please install pattern: pip install https://github.com/clips/pattern/archive/development.zip

So i uninstalled pattern and reinstalled it from that link.
But i get the same error next time i try.

Tryed on Manjaro Linux

**Comment by sinder96** [comment]
pattern changed the structure of their package as now instead of “import pattern.en” it should be replaced in all instances with “import pattern.text.en”. Might fix your problem.
