### ISSUE TITLE
running transcribe gives data['result'] keyerror

### ISSUE THREAD

**Issue by chrisgloom** [antiboredom/videogrep#93]
Ran into this just now
```python
 videogrep --input USNavyAdventure.mp4 --transcribe
Transcribing USNavyAdventure.mp4
Traceback (most recent call last):
  File "/usr/local/bin/videogrep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/videogrep/cli.py", line 129, in main
    transcribe.transcribe(f, args.model)
  File "/usr/local/lib/python3.9/site-packages/videogrep/transcribe.py", line 70, in transcribe
    words = [w for w in data["result"]]
KeyError: 'result'
```

python3 --version
Python 3.9.13

pip3 --version
pip 22.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)

vosk version
vosk-0.3.32

ffmpeg -v
ffmpeg version 5.0.1

running on a mac osx 10.15.7

**Comment by antiboredom** [comment]
weird! can you send over one of the files?

**Comment by chrisgloom** [comment]
uhhh oops. Incoming me feeling like an idiot...playing the files they have no sound. I didn't notice the yt-dlp format I'd chosen was video only until just now. Thanks for your help—maybe in the future the error will be less opaque by virtue of the added logging haha.
