### ISSUE TITLE
Not outputting 

### ISSUE THREAD

**Issue by bank-robber** [antiboredom/videogrep#98]
Hi 
I've gone through the tutorial and when I try to search it gives "No results found for experience" and when i search for most common words or phrases it gives an incorrect output: 

lucas@Lucass-MBP-2 ~ % videogrep --input meta.mp4 --ngrams 1
 2120
it 1

I'm using python 3.8.2, on osx 12.3.1 

Thanks for any help you can provide.

**Comment by antiboredom** [comment]
hmmmm can you send me the vtt file you're working with?

**Comment by bank-robber** [comment]
[subway.vtt.zip](https://github.com/antiboredom/videogrep/files/8781321/subway.vtt.zip)

Thanks!

**Comment by bank-robber** [comment]
[meta.vtt.zip](https://github.com/antiboredom/videogrep/files/8781327/meta.vtt.zip)

thanks!

**Comment by antiboredom** [comment]
I see - there's something weird about this file... Do you happen to know if you have the most recent version of `yt-dlp` installed?

**Comment by bank-robber** [comment]
Thank you! That was it. I must of been on a previous version. Updated to yt-dlp 2022.05.18 and it worked like a charm.

**Comment by antiboredom** [comment]
Ok great!
